name: Latexmk

on: push

jobs:
  build-pdfs:
    # Name the Job
    name: Build PDFs
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Latexmk
        uses: ianmcloughlin/latexmk@v1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}